/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:31:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.entity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody {overflow: hidden;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"btnDiv\">\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">添加");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageInfo.modelName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"listDiv\">\r\n");
      out.write("\t\t\t<table id=\"listTab\" class=\"list-table\"></table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar pageInfo = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\tinitPage();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initPage() {\r\n");
      out.write("\t\t\tvar html = \"\", fields = pageInfo.fields, datas = pageInfo.datas;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// init table head html\r\n");
      out.write("\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\thtml += \"<th width='60px'>序号</th>\";\r\n");
      out.write("\t\t\tfor(var i in fields) {\r\n");
      out.write("\t\t\t\thtml += \"<th width='\" + fields[i].width + \"px'>\" + fields[i].label + \"</th>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\thtml += \"<th width='50px'></th>\";\r\n");
      out.write("\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// init table body html\r\n");
      out.write("\t\t\tfor(var i in datas) {\r\n");
      out.write("\t\t\t\thtml += \"<tr id='\" + datas[i][0] + \"'>\";\r\n");
      out.write("\t\t\t\thtml += \"<td class='sn'>\" + (parseInt(i) + 1) + \"</td>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var j in fields) {\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + datas[i][parseInt(j) + 1] + \"</div></td>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// init operate td\r\n");
      out.write("\t\t\t\thtml += \"<td><div class='hide'>\";\r\n");
      out.write("\t\t\t\thtml += \"<i class='icon-pencil' style='cursor: pointer;margin-right: 10px;' onclick='editItem($(this));'></i>\";\r\n");
      out.write("\t\t\t\thtml += \"<i class='icon-trash' style='cursor: pointer;' onclick='removeItem($(this));'></i>\";\r\n");
      out.write("\t\t\t\thtml += \"</div></td>\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#listTab\").html(html);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// bind operate td mouse event\r\n");
      out.write("\t\t\t$(\"#listTab tr:gt(0)\").hover(function() { $(\"td:last div\", this).show(); }, function() { $(\"td:last div\", this).hide(); });\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction editItem($i) {\r\n");
      out.write("\t\t\tvar entityId = $i.closest(\"tr\").attr(\"id\");\r\n");
      out.write("\t\t\tlocation.href = top.basePath + \"entity/dispatch.do?operate=edit&model=\" + pageInfo.model + \"&entityId=\" + entityId;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction removeItem($i) {\r\n");
      out.write("\t\t\tvar entityId = $i.closest(\"tr\").attr(\"id\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tppmConfirm(\"删除\" + pageInfo.modelName, \"确定要删除该\" + pageInfo.modelName + \"么？\", function() {\r\n");
      out.write("\t\t\t\tlocation.href = top.basePath + \"entity/dispatch.do?operate=remove&model=\" + pageInfo.model + \"&entityId=\" + entityId;\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /pages/entity/list.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/entity/dispatch.do?operate=add&model=${pageInfo.model}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
