/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:20:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class structure_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\tbody {overflow: hidden;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"btnDiv\" class=\"hide\">\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">添加部门</a>\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">添加用户</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"listDiv\">\r\n");
      out.write("\t\t\t<table class=\"list-table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=\"60px\">序号</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"350px\">部门/用户</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"150px\">职位</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"200px\">Email</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"300px\">地址</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"50px\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tsearch();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction search($tr) {\r\n");
      out.write("\t\t\t_remoteCall(\"user/getStructure.do\", {parentId: $tr ? $tr.attr(\"id\") : \"\"}, function(data) {\r\n");
      out.write("\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr id='\" + data[i].id + \"' parentId='\" + data[i].parentId + \"' isDepart='\" + data[i].isDepart + \"'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='sn'>\" + (parseInt(i) + 1) + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div style='padding-left: \" + data[i].pad + \"px;\" + (data[i].isDepart == \"Y\" ? \"font-weight: bold;\" : \"\") + \"'><i onclick='toggleDepart($(this));' class='icon-plus tree-icon \" + (data[i].hasChild == \"Y\" ? \"\" : \"invisiable\") + \"'></i>\" + (data[i].isDepart == \"Y\" ? data[i].departName : data[i].username) + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + (data[i].positionName ? data[i].positionName : \"\") + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + data[i].email + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + data[i].address + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div class='hide'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<i class='icon-pencil' style='cursor: pointer;margin-right: 10px;' onclick='editItem($(this));'></i>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<i class='icon-trash' style='cursor: pointer;' onclick='removeItem($(this));'></i>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</div></td>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $trs = $(html);\r\n");
      out.write("\t\t\t\tif($tr) { $tr.after($trs); } else { $(\"table.list-table\").append($trs); }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tresetSn();\r\n");
      out.write("\t\t\t\tinitRole($trs);\r\n");
      out.write("\t\t\t\tautoFrameHeight();\r\n");
      out.write("\t\t\t}, true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initRole($trs) {\r\n");
      out.write("\t\t\t_remoteCall(\"role/hasStrutManageAuth.do\", null, function(data) {\r\n");
      out.write("\t\t\t\tif(data == \"Y\") {\r\n");
      out.write("\t\t\t\t\t$(\"#btnDiv\").show();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// bind mouse event\r\n");
      out.write("\t\t\t\t\t$trs.hover(function() { $(\"td:last div\", this).show(); },  function() { $(\"td:last div\", this).hide(); });\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$(\"#btnDiv\").remove();\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction toggleDepart($i) {\r\n");
      out.write("\t\t\tvar $tr = $i.closest(\"tr\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(!$tr.attr(\"hasLoad\")) {\r\n");
      out.write("\t\t\t\tsearch($tr);\r\n");
      out.write("\t\t\t\t$tr.attr(\"hasLoad\", \"Y\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"table.list-table tr[parentId='\" + $tr.attr(\"id\") + \"']\").toggle();\r\n");
      out.write("\t\t\t\tresetSn();\r\n");
      out.write("\t\t\t\tautoFrameHeight();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($i.hasClass(\"icon-plus\")) { $i.removeClass(\"icon-plus\").addClass(\"icon-minus\"); } else { $i.removeClass(\"icon-minus\").addClass(\"icon-plus\"); }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction resetSn() {\r\n");
      out.write("\t\t\t$(\"table.list-table tr:visible\").each(function(i) {\r\n");
      out.write("\t\t\t\t$(\"td:eq(0)\", $(this)).text(i);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction editItem($i) {\r\n");
      out.write("\t\t\tvar $tr = $i.closest(\"tr\"), isDepart = $tr.attr(\"isDepart\") == \"Y\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isDepart) {\r\n");
      out.write("\t\t\t\tlocation.href = top.basePath + \"user/createOrEditDepart.do?departId=\" + $tr.attr(\"id\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tlocation.href = top.basePath + \"entity/dispatch.do?operate=edit&model=com.cloud.security.model.User&entityId=\" + $tr.attr(\"id\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction removeItem($i) {\r\n");
      out.write("\t\t\tvar $tr = $i.closest(\"tr\"), isDepart = $tr.attr(\"isDepart\") == \"Y\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isDepart) {\r\n");
      out.write("\t\t\t\tppmConfirm(\"删除部门\", \"确定要删除该部门么？删除该部门后，其子部门和用户自动归属到该部门的上级部门。\", function() {\r\n");
      out.write("\t\t\t\t\tlocation.href = top.basePath + \"user/removeDepart.do?departId=\" + $tr.attr(\"id\");\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tppmConfirm(\"删除用户\", \"确定要删除该用户么？\", function() {\r\n");
      out.write("\t\t\t\t\t_remoteCall(\"user/removeUser.do\", {userId: $tr.attr(\"id\")}, function() {\r\n");
      out.write("\t\t\t\t\t\t$tr.remove();\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /pages/account/structure.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/user/createOrEditDepart.do");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /pages/account/structure.jsp(16,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/entity/dispatch.do?operate=add&model=com.cloud.security.model.User");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }
}
