/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:20:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.bug;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class bug_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.input-text {margin-bottom: 0!important;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"btnDiv\">\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">新建缺陷</a>\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">导出Excel</a>\r\n");
      out.write("\t\t\t<a href=\"#\" onclick=\"alert('正在努力地研发中...');\" class=\"button button-rounded button-flat-primary\">导出Word</a>\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">批量导入</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<span class=\"view-bar\">\r\n");
      out.write("\t\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a data-toggle=\"dropdown\" class=\"dropdown-toggle\" href=\"#\"><span id=\"viewName\">默认视图</span><i class=\"icon-th-list\"></i></a>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li id=\"defaultView\"><a href=\"#\" onclick=\"selectView();return false;\">默认视图</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li style=\"text-align: center;\"><a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"><i class=\"icon-plus\"></i> 新增视图</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"listDiv\">\r\n");
      out.write("\t\t\t<table id=\"bugTab\" class=\"list-table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=\"50px\"></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"120px\"><input id=\"code\" type=\"text\" class=\"input-text input-filter\" onkeydown=\"textSearch();\" /></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"400px\"><input id=\"name\" type=\"text\" class=\"input-text input-filter\" onkeydown=\"textSearch();\" /></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"150px\"><input id=\"project\" type=\"text\" class=\"input-text input-filter\" ondblclick=\"showProjects($(this));\" onkeydown=\"return false;\" /><i onclick=\"$(this).prev().dblclick();\" class=\"icon-search input-icon\"></i></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100px\"><input id=\"status\" type=\"text\" class=\"input-text input-filter\" ondblclick=\"showStatuses($(this));\" onkeydown=\"return false;\" /><i onclick=\"$(this).prev().dblclick();\" class=\"icon-search input-icon\"></i></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"90px\"><input id=\"level\" type=\"text\" class=\"input-text input-filter\" ondblclick=\"showLevels($(this));\" onkeydown=\"return false;\" /><i onclick=\"$(this).prev().dblclick();\" class=\"icon-search input-icon\"></i></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"90px\"><input id=\"priority\" type=\"text\" class=\"input-text input-filter\" ondblclick=\"showPriorities($(this));\" onkeydown=\"return false;\" /><i onclick=\"$(this).prev().dblclick();\" class=\"icon-search input-icon\"></i></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"90px\"><input id=\"owner\" type=\"text\" class=\"input-text input-filter\" ondblclick=\"showUsers($(this));\" onkeydown=\"return false;\" /><i onclick=\"$(this).prev().dblclick();\" class=\"icon-search input-icon\"></i></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"210px\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr id=\"head-tr\">\r\n");
      out.write("\t\t\t\t\t<th>序号</th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"code\">编号</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"name\">名称</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"projectId\">所属项目</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"status\">状态</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"level\">严重性</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"priority\">优先级</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"ownerId\">责任人</span></th>\r\n");
      out.write("\t\t\t\t\t<th><span class=\"head-sort\" field=\"modifyTime\">最近更新时间</span></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"pagination\"><ul></ul></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/projectSelectMul.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/userSelectMul.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/statusSelectMul.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/levelSelectMul.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/prioritySelectMul.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar sortInfo = [];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tsearch();\r\n");
      out.write("\t\tinitView();\r\n");
      out.write("\t\tinitSort();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initSort() {\r\n");
      out.write("\t\t\t$(\"span.head-sort\").click(function() {\r\n");
      out.write("\t\t\t\tsortInfo = [];\r\n");
      out.write("\t\t\t\tvar $i = $(\"#head-tr i\"), $spanI = $(\"i\", $(this));\r\n");
      out.write("\t\t\t\tsortInfo.push($(this).attr(\"field\"));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif($spanI.size() == 0) {\r\n");
      out.write("\t\t\t\t\t$(this).append($i.removeClass(\"icon-arrow-down\").addClass(\"icon-arrow-up\"));\r\n");
      out.write("\t\t\t\t\tsortInfo.push(\"asc\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tif($spanI.hasClass(\"icon-arrow-up\")) {\r\n");
      out.write("\t\t\t\t\t\t$spanI.removeClass(\"icon-arrow-up\").addClass(\"icon-arrow-down\");\r\n");
      out.write("\t\t\t\t\t\tsortInfo.push(\"desc\");\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$spanI.removeClass(\"icon-arrow-down\").addClass(\"icon-arrow-up\");\r\n");
      out.write("\t\t\t\t\t\tsortInfo.push(\"asc\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsearch();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initView() {\r\n");
      out.write("\t\t\t_remoteCall(\"bug/getViews.do\", null, function(data) {\r\n");
      out.write("\t\t\t\tvar info = eval(data), html = \"\", noSort = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i in info) {\r\n");
      out.write("\t\t\t\t\thtml += \"<li><a href='#' onclick='selectView(\\\"\" + info[i].id + \"\\\");return false;'><span onmouseover='this.title=this.innerText' style='width: 95px;display: inline-block;' class='text-omit'>\" + info[i].name + \"</span> <i class='icon-pencil' style='float: right;' onclick='editView(\\\"\" + info[i].id + \"\\\");return false;'></i></a></li>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(info[i].isDefault == \"Y\") {\r\n");
      out.write("\t\t\t\t\t\t$(\"#viewName\").text(info[i].name);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(info[i].sortField) {\r\n");
      out.write("\t\t\t\t\t\t\tnoSort = false;\r\n");
      out.write("\t\t\t\t\t\t\tvar $sf = $(\"span.head-sort[field='\" + info[i].sortField + \"']\");\r\n");
      out.write("\t\t\t\t\t\t\t$sf.append(\"<i class='icon-arrow-\" + (info[i].sortTo == \"asc\" ? \"up\" : \"down\") + \"'></i>\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(noSort) {\r\n");
      out.write("\t\t\t\t\t$(\"span.head-sort[field='modifyTime']\").append(\"<i class='icon-arrow-down'></i>\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#defaultView\").after(html);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction selectView(viewId) {\r\n");
      out.write("\t\t\tlocation.href = parent.basePath + \"bug/selectView.do?viewId=\" + (viewId ? viewId : \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction editView(viewId) {\r\n");
      out.write("\t\t\tlocation.href = parent.basePath + \"bug/createOrEditView.do?viewId=\" + viewId;\r\n");
      out.write("\t\t\tevent.cancelBubble = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction openBug($a) {\r\n");
      out.write("\t\t\tvar id = $a.closest(\"tr\").attr(\"id\");\r\n");
      out.write("\t\t\tlocation.href = parent.basePath + \"bug/openBug.do?bugId=\" + id;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction textSearch() {\r\n");
      out.write("\t\t\tif(event.keyCode != 13)  return;\r\n");
      out.write("\t\t\tsearch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction search(toPage) {\r\n");
      out.write("\t\t\t_remoteCall(\"bug/getBugs.do\", {page: toPage ? toPage : 1, sort: sortInfo.join(\",\"), code: $(\"#code\").val(), name: $(\"#name\").val(),\r\n");
      out.write("\t\t\t\t\tprojectIds: $(\"#project\").attr(\"val\") ? $(\"#project\").attr(\"val\") : \"\", status: $(\"#status\").attr(\"val\") ? $(\"#status\").attr(\"val\") : \"\",\r\n");
      out.write("\t\t\t\t\tlevels: $(\"#level\").attr(\"val\") ? $(\"#level\").attr(\"val\") : \"\", priorities: $(\"#priority\").attr(\"val\") ? $(\"#priority\").attr(\"val\") : \"\",\r\n");
      out.write("\t\t\t\t\townerIds: $(\"#owner\").attr(\"val\") ? $(\"#owner\").attr(\"val\") : \"\"}, function(data) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar dataInfo = eval(\"(\" + data + \")\"), page = dataInfo.page, info = dataInfo.bugs, html = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// init bugs table\r\n");
      out.write("\t\t\t\tfor(var i in info) {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr id='\" + info[i].id + \"'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='sn'>\" + getPageSn(page, i) + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].code + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div class='auto-link'><a href='#' onclick='openBug($(this));return false;'>\" + info[i].name + \"</a></div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].projectName + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].statusName + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].levelName + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].priorityName + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].owner + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + getTimeStr(info[i].modifyTime) + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// remove old trs first\r\n");
      out.write("\t\t\t\t$(\"#bugTab tr:gt(1)\").remove();\r\n");
      out.write("\t\t\t\t$(\"#bugTab\").append(html);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// init page bar\r\n");
      out.write("\t\t\t\tinitPage(page);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tparent.autoHeight();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /pages/bug/bug.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/bug/openOperate.do?op=create&fromStatus=0");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /pages/bug/bug.jsp(16,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/bugfile/exportExcel.do");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /pages/bug/bug.jsp(18,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/pages/bug/bugImport.jsp");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /pages/bug/bug.jsp(27,47) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/bug/createOrEditView.do");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }
}
