/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:20:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class levelSelectMul_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"levelModal\" class=\"hide\"><p style=\"padding: 5px;\">\r\n");
      out.write("\t<table id=\"levelTab\" class=\"list-table full-table\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th width=\"80px\" style=\"padding-left: 20px;\"><input id=\"l_all\" name=\"_user\" type=\"checkbox\" /></th>\r\n");
      out.write("\t\t\t<th width=\"460px\">严重性</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"1\" onclick=\"clickLevel($(this));\">\r\n");
      out.write("\t\t\t<td style=\"padding-left: 20px;\"><input name=\"_status\" type=\"checkbox\" /></td>\r\n");
      out.write("\t\t\t<td><div>致命</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"2\" onclick=\"clickLevel($(this));\">\r\n");
      out.write("\t\t\t<td style=\"padding-left: 20px;\"><input name=\"_status\" type=\"checkbox\" /></td>\r\n");
      out.write("\t\t\t<td><div>严重</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"3\" onclick=\"clickLevel($(this));\">\r\n");
      out.write("\t\t\t<td style=\"padding-left: 20px;\"><input name=\"_status\" type=\"checkbox\" /></td>\r\n");
      out.write("\t\t\t<td><div>一般</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr id=\"4\" onclick=\"clickLevel($(this));\">\r\n");
      out.write("\t\t\t<td style=\"padding-left: 20px;\"><input name=\"_status\" type=\"checkbox\" /></td>\r\n");
      out.write("\t\t\t<td><div>优化</div></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</p></div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar $_l_src;\r\n");
      out.write("\t\r\n");
      out.write("\tppmDialog(\"#levelModal\", \"选择严重性\", {\r\n");
      out.write("        \"确认\": function() { selectLevel(); },\r\n");
      out.write("        \"清空\": function() { selectLevel(true); },\r\n");
      out.write("        \"取消\": function() { $(this).dialog(\"close\"); }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction initLevel($inp) {\r\n");
      out.write("\t\t$_l_src = $inp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// init select statuses\r\n");
      out.write("\t\tvar id = $inp.attr(\"val\");  id = id ? id : \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#levelTab input:checkbox\").iCheck(\"uncheck\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#levelTab tr:gt(0)\").each(function() {\r\n");
      out.write("\t\t\tif(id.indexOf($(this).attr(\"id\")) >= 0)  $(\"input:checkbox\", $(this)).iCheck(\"check\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// init check box\r\n");
      out.write("\t\t$(\"#levelTab input\").iCheck({checkboxClass: \"icheckbox_square-blue\"});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// init select all\r\n");
      out.write("\t\t$(\"#l_all\").on(\"ifChecked\", function() { $(\"#levelModal input\").iCheck(\"check\"); }).on(\"ifUnchecked\", function() { $(\"#levelModal input\").iCheck(\"uncheck\"); });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction clickLevel($tr) {\r\n");
      out.write("\t\t$(\"input\", $tr).iCheck(\"toggle\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction selectLevel(isClear) {\r\n");
      out.write("\t\tif(isClear) {\r\n");
      out.write("\t\t\t$_l_src.attr(\"val\", \"\").val(\"\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar $sel = $(\"#levelModal input:checkbox:checked\"), $tr, ids = [], names = [];\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$sel.each(function() {\r\n");
      out.write("\t\t\t\t$tr = $(this).closest(\"tr\");\r\n");
      out.write("\t\t\t\tif(!$tr.attr(\"id\"))  return true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tids.push($tr.attr(\"id\"));\r\n");
      out.write("\t\t\t\tnames.push($(\"td:eq(1)\", $tr).text());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$_l_src.attr(\"val\", ids.join(\",\")).val(names.join(\", \"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// if has filter, call search to refresh table\r\n");
      out.write("\t\tif(typeof(search) == \"function\")  search();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#levelModal\").dialog(\"close\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
