/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:21:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class userSelect_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"userModal\" class=\"hide\"><p style=\"padding: 5px;\">\r\n");
      out.write("\t<table id=\"userTab\" class=\"list-table full-table\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th width=\"40px\"></th>\r\n");
      out.write("\t\t\t<th width=\"350px\">用户名</th>\r\n");
      out.write("\t\t\t<th width=\"150px\">职位</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</p></div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar $_u_src;\r\n");
      out.write("\t\r\n");
      out.write("\tppmDialog(\"#userModal\", \"选择用户\", {\r\n");
      out.write("        \"确认\": function() { selectUser(); },\r\n");
      out.write("        \"清空\": function() { selectUser(true); },\r\n");
      out.write("        \"取消\": function() { $(this).dialog(\"close\"); }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#userModal\").next().append(\"<span class='chx-container' style='float: left;'><input id='u_showStructure' type='checkbox' />组织架构</span>\");\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadUserData($inp, $tr) {\r\n");
      out.write("\t\t$_u_src = $inp;\r\n");
      out.write("\t\tvar id = $inp.attr(\"val\"), id = id ? id : \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!$(\"#u_showStructure\").is(\":checked\")) {\r\n");
      out.write("\t\t\t_remoteCall(\"user/getDepartUsers.do\", {}, function(data) {\r\n");
      out.write("\t\t\t\tvar html = \"\", $tab = $(\"#userTab\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// remove origin rows\r\n");
      out.write("\t\t\t\t$(\"tr:gt(0)\", $tab).remove();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr id='\" + data[i].id + \"' onclick='clickUser($(this));' ondblclick='selectUser();'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='sn'><input name='_user' type='radio' \" + (id == data[i].id ? \"checked\" : \"\") + \" /></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + data[i].username + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + data[i].positionName + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$tab.append(html);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// init check box\r\n");
      out.write("\t\t\t\t$(\"#userTab input\").not(\"#u_showStructure\").iCheck({radioClass: \"iradio_square-blue\"});\r\n");
      out.write("\t\t\t}, true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t_remoteCall(\"user/getStructure.do\", {parentId: $tr ? $tr.attr(\"id\") : \"\"}, function(data) {\r\n");
      out.write("\t\t\t\tvar html = \"\", $tab = $(\"#userTab\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i in data) {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr id='\" + data[i].id + \"' parentId='\" + data[i].parentId + \"' \" + (data[i].isDepart != \"Y\" ? (\"onclick='clickUser($(this));' ondblclick='selectUser();'\") : \"\") + \">\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='sn'>\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data[i].isDepart != \"Y\") {\r\n");
      out.write("\t\t\t\t\t\thtml += \"<input name='_user' type='radio' \" + (id == data[i].id ? \"checked\" : \"\") + \" />\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\thtml += \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div style='padding-left: \" + data[i].pad + \"px;\" + (data[i].isDepart == \"Y\" ? \"font-weight: bold;\" : \"\") + \"'><i onclick='u_toggleDepart($(this));' class='icon-plus tree-icon \" + (data[i].hasChild == \"Y\" ? \"\" : \"invisiable\") + \"'></i>\" + (data[i].isDepart == \"Y\" ? data[i].departName : data[i].username) + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + (data[i].positionName ? data[i].positionName : \"\") + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar $trs = $(html);\r\n");
      out.write("\t\t\t\tif($tr) { $tr.after($trs); } else { $(\"tr:gt(0)\", $tab).remove(); $tab.append($trs); }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// init check box\r\n");
      out.write("\t\t\t\t$(\"#userTab input\").not(\"#u_showStructure\").iCheck({radioClass: \"iradio_square-blue\"});\r\n");
      out.write("\t\t\t}, true);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction u_toggleDepart($i) {\r\n");
      out.write("\t\tvar $tr = $i.closest(\"tr\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!$tr.attr(\"hasLoad\")) {\r\n");
      out.write("\t\t\tloadUserData($_u_src, $tr);\r\n");
      out.write("\t\t\t$tr.attr(\"hasLoad\", \"Y\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#userTab tr[parentId='\" + $tr.attr(\"id\") + \"']\").toggle();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($i.hasClass(\"icon-plus\")) { $i.removeClass(\"icon-plus\").addClass(\"icon-minus\"); } else { $i.removeClass(\"icon-minus\").addClass(\"icon-plus\"); }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction clickUser($tr) {\r\n");
      out.write("\t\t$(\"input\", $tr).iCheck(\"check\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction selectUser(isClear) {\r\n");
      out.write("\t\tif(isClear) {\r\n");
      out.write("\t\t\t$_u_src.attr(\"val\", \"\").val(\"\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar $sel = $(\"#userModal input:radio:checked\").closest(\"tr\");\r\n");
      out.write("\t\t\t$_u_src.attr(\"val\", $sel.attr(\"id\")).val($(\"td:eq(1)\", $sel).text());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// if has filter, call search to refresh table\r\n");
      out.write("\t\tif(typeof(search) == \"function\")  search();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#userModal\").dialog(\"close\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// init show struture users\r\n");
      out.write("\t$(\"#u_showStructure\").iCheck({checkboxClass: \"icheckbox_square-blue\"}).on(\"ifChecked\", function() { loadUserData($_u_src); }).on(\"ifUnchecked\", function() { loadUserData($_u_src); });\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
