/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:31:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.input-text {width: 400px;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id=\"listDiv\">\r\n");
      out.write("\t\t\t<table class=\"list-table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=\"60px\">序号</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"100px\">类型</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"200px\">名称</th>\r\n");
      out.write("\t\t\t\t\t<th width=\"400px\">描述</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">1</td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">初始化页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看初始化状态的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">2</td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">待审核页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看待审核状态的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">3</td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">修改中页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看修改中状态的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">4</td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">回归测试中页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看回归测试中状态的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">5</td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">挂起页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看挂起状态的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">6</td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">关闭页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>查看关闭状态的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">7</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">创建 & 编辑页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>创建缺陷与编辑缺陷的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">8</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">指定修改页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>指定缺陷修改人及更换缺陷修改人的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">9</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">审核不通过页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>缺陷提交审核后，审核不通过的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">10</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">提交测试页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>修改完缺陷后，提交测试人员测试的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">11</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">测试通过页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>测试缺陷通过的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">12</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">测试不通过页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>测试缺陷不通过的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">13</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">挂起页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>将缺陷挂起的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">14</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">更换测试人页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>更换测试缺陷责任人的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">15</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">直接关闭页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>直接关闭缺陷的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"sn\">16</td>\r\n");
      out.write("\t\t\t\t\t<td><div>操作页面</div></td>\r\n");
      out.write("\t\t\t\t\t<td><div class=\"auto-link\"><a href=\"#\" onclick=\"openPage($(this));return false;\">重启开启页面</a></div></td>\r\n");
      out.write("\t\t\t\t\t<td><div>重新开启已关闭缺陷的页面</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction openPage($a) {\r\n");
      out.write("\t\t\tvar flag = $(\"td:eq(0)\", $a.closest(\"tr\")).text().trim();\r\n");
      out.write("\t\t\tlocation.href = top.basePath + \"system/openPage.do?pageFlag=\" + flag;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tautoFrameHeight();\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
