/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2014-08-30 15:20:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class project_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.input-text {margin-bottom: 0!important;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<div id=\"btnDiv\" class=\"hide\">\r\n");
      out.write("\t\t\t<a href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" class=\"button button-rounded button-flat-primary\">新建项目</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"chx-container btn-right\">\r\n");
      out.write("\t\t\t\t<input id=\"showClose\" type=\"checkbox\" />显示已关闭\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"listDiv\">\r\n");
      out.write("\t\t\t<table id=\"projectTab\" class=\"list-table\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width=\"60px\"></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"450px\"><input id=\"name\" type=\"text\" class=\"input-text input-filter\" onkeydown=\"textSearch();\" /></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"150px\"><input id=\"owner\" type=\"text\" class=\"input-text input-filter\" ondblclick=\"showUsers($(this));\" onkeydown=\"return false;\" /><i onclick=\"$(this).prev().dblclick();\" class=\"icon-search input-icon\" style=\"margin-left: -19px;margin-top: 5px;\"></i></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"120px\"></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"120px\"></th>\r\n");
      out.write("\t\t\t\t\t<th width=\"150px\"></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>序号</th>\r\n");
      out.write("\t\t\t\t\t<th>名称</th>\r\n");
      out.write("\t\t\t\t\t<th>项目经理</th>\r\n");
      out.write("\t\t\t\t\t<th>起始日期</th>\r\n");
      out.write("\t\t\t\t\t<th>结束日期</th>\r\n");
      out.write("\t\t\t\t\t<th>创建时间</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"pagination\"><ul></ul></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/pages/common/userSelectMul.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tsearch();\r\n");
      out.write("\t\tinitRole();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#showClose\").iCheck({checkboxClass: \"icheckbox_square-blue\"}).on(\"ifChecked\", function() { search(1, true); }).on(\"ifUnchecked\", function() { search(); });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction initRole() {\r\n");
      out.write("\t\t\t_remoteCall(\"role/hasPjtManageAuth.do\", null, function(data) {\r\n");
      out.write("\t\t\t\tdata == \"Y\" ? $(\"#btnDiv\").show() : $(\"#btnDiv\").remove(); \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction search(toPage, showClose) {\r\n");
      out.write("\t\t\t_remoteCall(\"project/getProjects.do\", {page: toPage ? toPage : 1, showClose : showClose ? \"Y\" : \"N\", name: $(\"#name\").val(), ownerIds: $(\"#owner\").attr(\"val\") ? $(\"#owner\").attr(\"val\") : \"\"}, function(data) {\r\n");
      out.write("\t\t\t\tvar d = eval(\"(\" + data + \")\"), page = d.page, info = d.projects, html = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i in info) {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr id='\" + info[i].id + \"'>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td class='sn'>\" + (parseInt(i) + 1) + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div class='auto-link'><a href='#' onclick='openProject($(this));return false;'>\" + info[i].name + \"</a></div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + info[i].manager + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + getDateStr(info[i].startDate) + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + getDateStr(info[i].endDate) + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td><div>\" + getTimeStr(info[i].createTime) + \"</div></td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#projectTab tr:gt(1)\").remove();\r\n");
      out.write("\t\t\t\t$(\"#projectTab\").append(html);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// init page bar\r\n");
      out.write("\t\t\t\tinitPage(page);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tparent.autoHeight();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction textSearch() {\r\n");
      out.write("\t\t\tif(event.keyCode != 13)  return;\r\n");
      out.write("\t\t\tsearch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction openProject($a) {\r\n");
      out.write("\t\t\tvar id = $a.closest(\"tr\").attr(\"id\");\r\n");
      out.write("\t\t\tlocation.href = parent.basePath + \"project/openProject.do?projectId=\" + id;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /pages/project/project.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/project/createOrEdit.do");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
